Fixing build issues
Signed-off-by: Nikhil Manglore <nmanglor@amazon.com>

diff --git a/8.1/alpine/Dockerfile b/8.1/alpine/Dockerfile
--- a/8.1/alpine/Dockerfile
+++ b/8.1/alpine/Dockerfile
@@ -24,11 +24,6 @@ RUN set -eux; \
 	        clang19-extra-tools   \
 	        linux-headers         \
 	        bash                  \
-            protobuf-dev          \
-            protobuf              \
-            grpc-dev              \
-            grpc                  \
-            grpc-plugins          \
 	;\
     update-ca-certificates; \
     ln -s /usr/lib/ninja-build/bin/ninja /usr/bin/ninja-build;
@@ -59,7 +54,10 @@ RUN RUSTFLAGS="-C target-feature=-crt-static" cargo build --all --all-targets --
 
 # Build Search module
 WORKDIR /opt/valkey-search
-RUN set -eux;       \
+# on alpine, the first build fails due to this issue: https://github.com/grpc/grpc/issues/38438
+# we just replace mutable int32_t with mutable int in .build-release/.deps/grpc/third_party/re2/util/pcre.h
+# based on this upstream change https://github.com/google/re2/commit/b025c6a3ae05995660e3b882eb3277f4399ced1a
+RUN set -eux; \
     ./build.sh
 
 FROM docker.io/valkey/valkey:8.1.1-alpine
diff --git a/8.1/debian/Dockerfile b/8.1/debian/Dockerfile
--- a/8.1/debian/Dockerfile
+++ b/8.1/debian/Dockerfile
@@ -55,7 +55,10 @@ RUN cargo build --all --all-targets --release;
 
 # Build Search module
 WORKDIR /opt/valkey-search
-RUN set -eux;       \
+# on alpine, the first build fails due to this issue: https://github.com/grpc/grpc/issues/38438
+# we just replace mutable int32_t with mutable int in .build-release/.deps/grpc/third_party/re2/util/pcre.h
+# based on this upstream change https://github.com/google/re2/commit/b025c6a3ae05995660e3b882eb3277f4399ced1a
+RUN set -eux; \
     ./build.sh
 
 FROM docker.io/valkey/valkey:8.1.1-bookworm
